### ISSUE TITLE
Bug (?) in `ucp_markdown_status`

### ISSUE THREAD

**Issue by lionel-rowe** [AlfredoRamos/phpbb-ext-markdown#111]
Not sure if this causes any actually-existing bug, but I noticed this while grepping for something unrelated in my phpBB install:

https://github.com/AlfredoRamos/phpbb-ext-markdown/blob/f5b7fd921dc780744da485c49053934b4b841ffb/event/listener.php#L310

`$event['mode' !== 'post']`, and therefore the entire condition, is presumably always going to be falsy, because it evaluates to `$event[true]`, which presumably doesn't exist.

Should be `$event['mode'] !== 'post'` instead.

**Comment by AlfredoRamos** [comment]
Thanks for the report.

> Not sure if this causes any actually-existing bug

It shouldn't as that's only a small check for performance reasons.
