### ISSUE TITLE
Feature Request: Markdown input bar

### ISSUE THREAD

**Issue by jonpas** [AlfredoRamos/phpbb-ext-markdown#15]
Like BBCode has a row above input box for styling, replace that with Markdown styling in some way.

**Comment by AlfredoRamos** [comment]
I'm not sure about this, one of the reasons I started this was to avoid the use of the editor buttons because with markdown you can do all the styling with just the keyboard.

Besides, adding an editor would add extra complexity which I'm trying to keep it low.

I will think about it.

**Comment by jonpas** [comment]
I tend to agree, but we all know regular users prefer clicking buttons (as sad as that is).
