### ISSUE TITLE
Sometimes not working

### ISSUE THREAD

**Issue by kisvegabor** [AlfredoRamos/phpbb-ext-markdown#2]
Hi,

First of all, thank you for this great extension!

I started to use it on my [Forum](https://forum.littlevgl.com/) and noticed that sometimes the new post are not formatted. I need to purge the cache to make it work again.

It seems Markdown is enabled: 
![image](https://user-images.githubusercontent.com/7599318/54662356-09419980-4ade-11e9-89dd-98dcbab0acf9.png)
 

Do you have any idea?

**Comment by AlfredoRamos** [comment]
Hi @kisvegabor,

It's a known issue for some extensions that uses the parser see https://github.com/kasimi/mChat/issues/27#issuecomment-462031443

I see you're using versión 0.6.0-dev, try update to the latest version (currently 0.7.0-beta) available here:

- https://www.phpbb.com/community/viewtopic.php?t=2499776

If that does not help with the problem, please provide the following information to try to reproduce the issue:

- phpBB Version
- PHP version
- Complete list of enabled extensions along with its dependencies
- Style version

**Comment by kisvegabor** [comment]
Thank you very much!

I updated to `0.7.0-beta`. I'll come back if I experience the issue again.

**Comment by AlfredoRamos** [comment]
@kisvegabor is this issue fixed? I couldn't reproduce it on the boards it iss being used in.

**Comment by kisvegabor** [comment]
The new version seems working so far, however it usually takes a few days to see the issue.

Anyway, here is the list of the extensions:

Name | Version |
-- | -- | 
Digests | 3.2.11 |
Enable e-mail notifications on registration | 1.0.0-dev |
Imgur | 1.1.1 |
Markdown | 0.7.0-beta | 
OneAll Social Login | 4.5.2 |
phpBB 3.2 Post Love | 2.0.0-a2 |
Simple mentions | 1.0.3 |
Stop Forum Spam | 1.1.9 | 
VigLink | 1.0.4 |


I made some tweaks on the extensions and theme of the board but they shouldn't be that are not related to this issue.  (mainly styles and templates)

I think we can close this issue and reopen it if the issue will be seen again.  Do you agree?

**Comment by AlfredoRamos** [comment]
> I think we can close this issue and reopen it if the issue will be seen again. Do you agree?

Agree, I'll try to reproduce it with the information given anyways.

Please reopen if the issue persist.
