### ISSUE TITLE
Posting option to disable Markdown does not keep value

### ISSUE THREAD

**Issue by johnd0e** [AlfredoRamos/phpbb-ext-markdown#35]
When I make post with option "[x] Disable Markdown", and then try to edit it -  I see that option value is cleared.

If I then press "Submit" (without any change) - I see markdown get parsed.

I tried #34, but this bug still there.

**Comment by AlfredoRamos** [comment]
Thanks for the report.

Personal note: Use another event to assign `S_MARKDOWN_CHECKED`, probably `core.posting_modify_default_variables`
