### ISSUE TITLE
createParagraphs rule is active even when markdown is not enabled

### ISSUE THREAD

**Issue by johnd0e** [AlfredoRamos/phpbb-ext-markdown#36]
As discovered in https://www.phpbb.com/customise/db/extension/markdown/support/topic/206381,
`createParagraphs` rule is needed when rendering markdown.

But currently is is applied to any post, even with `[x] Disable markdown` switch, and even when markdown is not enabled in ACP Board features.

**Comment by AlfredoRamos** [comment]
https://github.com/s9e/TextFormatter/issues/151
