### ISSUE TITLE
negative impact of createParagraphs rule

### ISSUE THREAD

**Issue by johnd0e** [AlfredoRamos/phpbb-ext-markdown#37]
We want to enable Markdown extension on our board, to make some experiments, but we are not sure that we will keep it after.

Unfortunately with this extension enabled every new (or edited) post get additional `<p>` wrapping.

This has no visual impact while the extension enabled.
But if we disable it - it's css removed, and posts text gets too large.

Worse of all - every post affected, even with disabled markdown option (#36)

**Comment by AlfredoRamos** [comment]
That's not really an issue of this extension.

It also happens when you post a message with, for example, a custom BBCode, and latter you delete that BBCode.

Old posts would still have the previous markup but broken.

To "fix it" you would need to reparse the post.

You have a few options to do so:

- Wait until the phpBB's built-in cron job catches your posts
- Trigger a post checksum change by making small modifications in the post content
- Use an extension
- Use the tool available in the command line

https://area51.phpbb.com/docs/dev/3.3.x/cli/index.html

**Comment by johnd0e** [comment]
> That's not really an issue of this extension.

I agree that root cause is not the extension itself.
But still, it is affected, so I suggest to keep this issue open, just to inform users, as it's not obvious.


> It also happens when you post a message with, for example, a custom BBCode, and latter you delete that BBCode.

It is not the same, for 3 reasons:
- When I delete a bbcode old posts do not get rerendered.
It's normal flow, when some legacy bbcode is replaced with something modern, and it's good feature that old markup stays untouched.
- When I delete markdown extension I can accept that I will get raw markdown text, but it is not the case: in fact markdown stays rendered. Instead, all text become too large
- Not-markdown posts are affected as well (#36)


> To "fix it" you would need to reparse the post.

This is something that may be undesirable for already mentioned reason


> You have a few options to do so:

I am not sure yet what is best way to address this issue.
May be we should just promote `<p>` to phpBB buildin css.

**Comment by AlfredoRamos** [comment]
> May be we should just promote `<p>` to phpBB buildin css.

I don't even know why phpBB changes the font size for paragraphs.

I haven't found any single piece of code where it's being used, so not sure why they decided to make paragraph using other styling, for exactly `.content p`

However, if you use other markup like headings on your post, disabling the extension would break them too as phpBB also change their font size and use `float` on some of them.

**Comment by johnd0e** [comment]
> if you use other markup like headings on your post

What headings do you mean?
I've tested mardown h2, and after disabling extension they become plain text.
I mean 'plain text' in markup, not css.

**Comment by AlfredoRamos** [comment]
Mmm.. I remember there were kept as headings before on an old phpBB 3.2.0 board.

Maybe is just my memory playing tricks on me.
