### ISSUE TITLE
Is it possible to use PipeTables without Litedown?

### ISSUE THREAD

**Issue by johnd0e** [AlfredoRamos/phpbb-ext-markdown#38]
Even if you are not going to support such setup in your extension - someone might want to write separate extension for PipeTables.

Then I wonder if line 208 would prevent those hypothetical extension to function (also line 270, etc):

https://github.com/AlfredoRamos/phpbb-ext-markdown/blob/2e30fe0bbd904a735fe8193be9e930317d5a9091/event/listener.php#L204-L210

**Comment by AlfredoRamos** [comment]
> Then I wonder if line 208 would prevent those hypothetical extension to function (also line 270, etc)

This line (208):

```php
 	 	unset($configurator->PipeTables);
```

Will disable the plugin entirely.

This line (270):

```php
			$parser->disablePlugin('PipeTables');
```

Will only disable the parsing, but the plugin might still be loaded.

> Even if you are not going to support such setup in your extension - someone might want to write separate extension for PipeTables.

You might want to read the official documentation.

- https://area51.phpbb.com/docs/dev/3.3.x/extensions/tutorial_bbcodes.html
- https://s9etextformatter.readthedocs.io/Plugins/PipeTables/Synopsis/

If you only need PipeTables it would be easy to accomplish, however I would suggest to use another extensions, there some at phpbb.com that do exactly that.
___

As this is a general question for phpBB extension development, I'm closing this issue.

**Comment by johnd0e** [comment]
> there some at phpbb.com that do exactly that.

Ok, so what will happen if I use both?
1. Some extension specialized on PipeTables
2. This Markdown extension, but either completely disabled, or partially?

I worry, as you wrote:

> Will disable the plugin entirely.

So there will be conflict?

**Comment by AlfredoRamos** [comment]
> Ok, so what will happen if I use both?

I think the plugin will be enabled only once.

> So there will be conflict?

I don't think so, for example if you disable PipeTables in this extension and you install another extension that enables the same plugin, it will be enabled.

It will disable the plugin entirely, within the extension, but others can enable it again.

**Comment by johnd0e** [comment]
> I don't think so, for example if you disable PipeTables in this extension and you install another extension that enables the same plugin, it will be enabled.
> 
> It will disable the plugin entirely, within the extension, but others can enable it again.

I've made a real test, and found conflict.

- Setup new board
- Enable pipe tables via https://github.com/phpBB-Studio/TextFormatter, and post a sample message with pipe table (to make sure that it's rendered as expected)
- Install your Markdown extension, and edit same message to make sure that all is ok.
- Edit message and set `Disable markdown` option.

After these actions you see pipe table not rendered.

**Comment by AlfredoRamos** [comment]
I wouldn't say that's a conflict, because the PipeTables plugin is still loaded.

It would be a conflict if, after disabling and removing Markdown, PipeTables would be disabled.
