### ISSUE TITLE
Feature Request: Task lists

### ISSUE THREAD

**Issue by ZachBacon** [AlfredoRamos/phpbb-ext-markdown#40]
Just a request, if possible for markdown support in phpBB (great extension by the way.)

Can we have support for checkboxes?

```
- [x] done
- [ ] todo
```

**Comment by AlfredoRamos** [comment]
You might want to make this request to [s9e/TextFormatter](https://github.com/s9e/TextFormatter) first, which is the engine that actually parses Markdown-like syntax.

**Comment by ZachBacon** [comment]
will do.

**Comment by ZachBacon** [comment]
Got the run around https://github.com/s9e/TextFormatter/issues/141#issuecomment-608193052

**Comment by AlfredoRamos** [comment]
Ok, I'll see what I can do.

**Comment by JoshyPHP** [comment]
I don't know how a checkbox is supposed to work but you may be able to use something like that:

```php
$configurator->Preg->replace(
	'/\\[(?<content>[ x])\\]/',
	'<input type="checkbox">
		<xsl:if test="@content = \'x\'"><xsl:attribute name="checked"/></xsl:if>
	</input>',
	'CHECKBOX'
);
```

Alternatively, you may want to use a tag filter to normalize the value of `@content` at parsing time if you want to accept values other than a space and `x`.

**Comment by AlfredoRamos** [comment]
Thanks @JoshyPHP,

It should work the same way as here on GitHub:

- [x] Done
- [ ] To-do

I've come up with the following, which checks that there's a hyphen (`-`) before the checkbox and there's text after it.

```php
$configurator->Preg->replace(
	'#(?<=\\- )\\[(?<content>[ x])\\](?= .+)#',
	'<input type="checkbox" class="md task-item" disabled="">
		<xsl:if test="@content = \'x\'">
			<xsl:attribute name="checked"></xsl:attribute>
		</xsl:if>
	</input>'
);
```

Now I'll have to find a way to remove the list marker, because there's no parent selector in CSS.

![preview](https://i.imgur.com/bO4XioR.png)

**Comment by JoshyPHP** [comment]
You can probably do this for the bullet type:
```php
$configurator->tags['LIST']->filterChain->prepend(
	'filterTaskList($tag, $innerText)'
);
function filterTaskList(s9e\TextFormatter\Parser\Tag $tag, string $innerText)
{
	if (preg_match('/^\\s*-\\s+\\[[ x]\\]/', $innerText))
	{
		$tag->setAttribute('type', 'none');
	}
}
```

Also, you definitely want to provide a tag name when using the Preg plugin otherwise one will be generated for you and it won't be forward-compatible.

**Comment by JoshyPHP** [comment]
Thought about it some more. I think that rather than use the Preg plugin to capture the tasklist markup, I would add a filter to the `LI` tag that's used to represent list item. The filter would examine the 3 characters after the list item to determine whether it's followed by `[ ]` or `[x]`.

```php

$tag = $configurator->tags->add('TASK');
$tag->attributes->add('state')->required = false;
$tag->template = '<input type="checkbox"><xsl:if test="@state"><xsl:attribute name="checked"/></xsl:if></input>';

$configurator->tags['LI']->filterChain->append('filterTaskList($parser, $tag, $text)');

function filterTaskList($parser, $tag, $text)
{
    $pos = $tag->getPos() + $tag->getLen();
    $str = substr($text, $pos, 3);
    if ($str !== '[ ]' && $str !== '[x]')
    {
        return;
    }

    $task = $parser->addSelfClosingTag('TASK', $pos, 3);
    if ($str === '[x]')
    {
        $task->setAttribute('state', 'checked');
    }
}
```

**Comment by AlfredoRamos** [comment]
@JoshyPHP Thank you so much, I really appreciate your help.

I've published working code in the [task-list](https://github.com/AlfredoRamos/phpbb-ext-markdown/tree/task-list) branch.

I will experiment a little more.

**Comment by JoshyPHP** [comment]
@AlfredoRamos I've thought about task lists and how to implement/manage them, and I'm considering creating a plugin for my library. It wouldn't be part of the Litedown plugin so it wouldn't interfere with your implementation if you want to roll your own. The reason I'm thinking about supporting it as part of the library is to provide a simple API to toggle tasks, maybe reorder them too. I haven't decided yet but I'm subscribed to this issue and I'll give you a heads-up asap (probably in the next few days) in case you want to use my implementation instead.

**Comment by AlfredoRamos** [comment]
That sounds good!

I would prefer to have a plugin to avoid introducing new bugs in the extension by accident.

I'll leave that branch on hold for now.
